### PR TITLE
added equation mode

### PR DESCRIPTION
**Pull request by venkateshdwivedi**
To Solve Quadratic Equation , click on Equation button and fill the values

### CODE REVIEW

**Review by taapasX28 — COMMENTED** [review]
Make the answer boxes non editable.

**Comment by venkateshdwivedi** [comment]
i have made the changes..

**Review by taapasX28 — COMMENTED** [review]
Can you also provide the documentation for it ?

**Comment by venkateshdwivedi** [comment]
Sure. But it don't need much intro I think..

**Comment by taapas1128** [comment]
Just add what equation button does

**Comment by venkateshdwivedi** [comment]
ok , i am on it

**Comment by venkateshdwivedi** [comment]
Done!!

**Review by taapasX28 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
