### PR TITLE
Fixed advanced Math errors

### PR DESCRIPTION
**Pull request by 07kshitij**
Handled all exceptions and errors I could think of. Please let me know if some bugs still remain.

### CODE REVIEW

**Comment by taapas1128** [comment]
Yes most of the bugs are dealt with but can you make the error messages more user friendly ? Like remove error type from error messages and tell the user just where he is wrong in input. Specifically change the "Syntax error" message.

**Comment by 07kshitij** [comment]
> Yes most of the bugs are dealt with but can you make the error messages more user-friendly? Like remove error type from error messages and tell the user just where he is wrong in the input. Specifically, change the "Syntax error" message.

Hmm, will read about it and try to do make possible changes.

**Comment by 07kshitij** [comment]
Hmm, my bad. I've created a fresh PR for the backspace button. 
Also, I would request others too to look into finding specific errors, I read about it but didn't get anything to get rid of those (Esp. syntax errors can arise due to a lot of reasons, and with the level of information about Python I have now, I don't know if there is any way to pinpoint one particular type of syntax error)

**Comment by 07kshitij** [comment]
Anyway, I'm closing this PR. Will work on a fresh one if the error messages are handled.

**Pull request closed without merging**
